version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "skill-shift"
    IMAGE_TAG: "latest"
    AWS_REGION: "us-east-1"
  runtime-versions:
    nodejs: 18  # Specify Node.js version 18 to match your Dockerfile

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --verbose

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 967083126936.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Next.js app...
      - npm run build
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Tagging Docker image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 967083126936.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 967083126936.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
