version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "skill-shift"
    IMAGE_TAG: "latest"
    AWS_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 640168451108.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Next.js app...
      - npm run build  # Ensure your app builds correctly
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .  # Build Docker image
      - echo Tagging Docker image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 640168451108.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  # Tag image for ECR

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 640168451108.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  # Push image to ECR

artifacts:
  files:
    - '**/*'
